select sysdate from dual;

select 2+3 from dual;

select trunc(sysdate) from dual;

desc dual;

select * from dual;

select count(*) from dual;

select 'sdfsdfsdfsdfsdfsdf' from dual;

truncate table dual;

delete from dual;

INSERT INTO DUAL VALUES ('X');

SELECT (10 + 5)/2 FROM dual;

SELECT
  UPPER('This is a string')
FROM
  dual;
  
  SELECT
  LOWER('This is a string'),UPPER('hellos'),INITCAP('ddsdf'),LENGTH('ddsfdds'),
  LENGTH('HJDHDD')-LENGTH(REPLACE('HJDHDD','T',' '))
FROM DUAL;

